---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Vector installed
    package:
      name: "vector"
      state: "installed"
    check_mode: yes